name: Check LAVA templates

on:
  workflow_call:

# implicitely set all other permissions to none
permissions:
  contents: read # actions/checkout

jobs:
  schema-check:
    runs-on: ubuntu-latest
    container: lavasoftware/lava-server:2025.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Schema check
        run: |
          DEVICE_TYPE="my-device"
          BUILD_FILE_NAME="build.tar.gz"
          BUILD_DOWNLOAD_URL="https://example.com/downloads/1"
          GITHUB_SHA="7e6f96ccf3e911a8a1a18accdbb91991aa0db66e"

          find ci/lava/ -name "*.yaml" -exec sed \
              -e "s|{{BUILD_DOWNLOAD_URL}}|${BUILD_DOWNLOAD_URL}|g" \
              -e "s|{{BUILD_FILE_NAME}}|${BUILD_FILE_NAME}|g" \
              -e "s|{{DEVICE_TYPE}}|${DEVICE_TYPE}|g" \
              -e "s|{{GITHUB_RUN_ID}}|${GITHUB_RUN_ID}|g" \
              -e "s|{{GITHUB_SHA}}|${GITHUB_SHA}|g" \
              -i '{}' \;

          ci/schemacheck.py ci/lava/
